version: 2
sources:
  - name: admin_backend
    database: fh_bronze
    schema: '{{ env_var(''_ENV'') }}_admin_backend_public'
    tables:
      - name: alembic_version
      - name: biomarker
      - name: biomarker_reflex
      - name: biomarker_result
      - name: category
      - name: category_biomarker
      - name: cause
      - name: covid
      - name: critical
      - name: critical_result
      - name: disease
      - name: exercise
      - name: female_reproductive_health
      - name: food
      - name: medical_hx
      - name: motivational
      - name: package
      - name: package_panel
      - name: panel
      - name: panel_biomarker
      - name: panel_group
      - name: panel_group_panel
      - name: patient
      - name: patient_address
      - name: patient_behavior_info
      - name: patient_contact_info
      - name: physician_note
      - name: physician_note_feedback
      - name: physician_note_ledger
      - name: physician_note_record
      - name: prior_pregnancy
      - name: recommendation
      - name: recommendation_cause
      - name: recommendation_disease
      - name: recommendation_exercise
      - name: recommendation_food_to_avoid
      - name: recommendation_food_to_eat
      - name: recommendation_panel
      - name: recommendation_selfcare
      - name: recommendation_supplement
      - name: recommendation_symptom
      - name: requisition
      - name: requisition_comment
      - name: requisition_comment_log
      - name: requisition_group
      - name: requisition_visit
      - name: result
      - name: result_package
      - name: result_visit
      - name: selfcare
      - name: sex_specific
      - name: supplement
      - name: symptom
      - name: visit
      - name: visit_document
      - name: visit_meta_data
      - name: visit_package
